categories:
  - title: 'Added'
    labels:
      - 'enhancement'
  - title: 'Fixed'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Changed'
    labels:
      - 'maintenance'
  - title: 'Internal'
    labels:
      - 'internal'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
      - 'enhancement'
  minor:
    labels:
      - 'minor'
      - 'bug'
  patch:
    labels:
      - 'patch'
  default: patch
    
template: |
  {{#each release.commits }}
  - {{#if this.hash }} {{ this.hash.substring(0, 7) }}: {{/if}}{{ this.subject }} {{#if this.author}}(@{{ this.author.name }}){{/if}}
  {{/each}}
