template: |
  # What's Changed
  $CHANGES
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
tag-prefix: v
categories:
  - title: 'Added'
    labels:
      - 'enhancement'
  - title: 'Fixed'
    labels:
      - 'bug'
  - title: 'Changed'
    labels:
      - 'maintenance'
  - title: 'Internal'
    labels:
      - 'internal'
version-resolver:
  major:
    labels:
      - 'major'
      - 'enhancement'
  minor:
    labels:
      - 'minor'
      - 'bug'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/WF-[0-9]{1,4}/'
  - label: 'major'
    title:
      - '/major/i'
  - label: 'minor'
    title:
      - '/minor/i'
  - label: 'patch'
    title:
      - '/patch/i'