categories:
  - title: 'Added'
    labels:
      - 'enhancement'
  - title: 'Fixed'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Changed'
    labels:
      - 'maintenance'
  - title: 'Internal'
    labels:
      - 'internal'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
      - 'enhancement'
  minor:
    labels:
      - 'minor'
      - 'bug'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/WF-[0-9]{1,4}/'
  - label: 'major'
    title:
      - '/major/i'
  - label: 'minor'
    title:
      - '/minor/i'
  - label: 'patch'
    title:
      - '/patch/i'
  - label: 'patch'
    title:
      - '/patch/i'
    
template: |
  {%- for group in commits|groupby('library') %}
  ### {{ group.grouper }}
  {% for commit in group.list -%}
  - {{ commit.message }}
  {% endfor %}
  {%- endfor %}