name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
        
  workflow_run:
    workflows: ["labeler.yml"]
    types:
      - completed

jobs:
  # correct_repository:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: fail on fork
  #     if: github.repository_owner != 'Backbase'
  #     run: exit 1

  # echo_labels:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Debug issue number
  #       run: |
  #         x=${{ toJson(github.event.pull_request.labels.*.name) }}
  #         echo $x

  get_labels:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Use pull request number
        if: github.event_name == 'push'
        run: echo "Pull request number is ${{ github.event.pull_request.number }}"

      - name: Get Labels
        if: github.event_name == 'push'
        uses: actions/github-script@v4
        with:
          script: |
            const { data: labels } = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ github.event.pull_request.number }}
            })
          console.log(`Labels: ${labels.map(label => label.name).join(', ')}`)

  update_release_draft-transactions:
    permissions:
      contents: write
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'transactions')
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-transactions.yml
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft-transfer:
      permissions:
        contents: write
        pull-requests: write
      if: contains(github.event.pull_request.labels.*.name, 'transfer')
      runs-on: ubuntu-latest
      steps:
        - uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter-transfer.yml
            commitish: main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
