name: Release Drafter

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]
  
  workflow_run:
    workflows: ["labeler.yml"]
    types:
      - completed

jobs:
  # correct_repository:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: fail on fork
  #     if: github.repository_owner != 'Backbase'
  #     run: exit 1

  update_release_draft-transactions:
    permissions:
      contents: write
      pull-requests: write
    if: contains(github.event.pull_request.labels.*.name, 'transactions')
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-transactions.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_release_draft-transfer:
      permissions:
        contents: write
        pull-requests: write
      if: contains(github.event.pull_request.labels.*.name, 'transfer')
      runs-on: ubuntu-latest
      steps:
        - uses: release-drafter/release-drafter@v5
          with:
            config-name: release-drafter-transfer.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
